window.LOUNGE_MENU = {
    categories: [
        {
            slug: "bread",
            icon: "fa-egg",
            image: "images/coffee 2.jpg",
            name: { en: "Breakfast & Brunch", vi: "Bua sang va brunch" },
            intro: { en: "Buttermilk pancakes, banana bread, bacon-and-egg style plates and easy morning favourites.", vi: "Pancake sua bo, banh chuoi, cac dia an sang voi bacon va trung, va nhieu mon buoi sang de an." },
            items: [["Buttermilk Pancakes", "Ask in store"], ["Banana Bread", "Ask in store"], ["Bacon & Egg Roll", "Ask in store"], ["Eggs Your Way", "Ask in store"], ["Big Breakfast", "Ask in store"], ["Sourdough Toast", "Ask in store"]]
        },
        {
            slug: "coffee",
            icon: "fa-mug-hot",
            image: "images/coffee 4.webp",
            name: { en: "Coffee", vi: "Ca phe" },
            intro: { en: "Strong, smooth cafe coffee for the daily run, dine-in brunch or takeaway.", vi: "Ca phe thom dam cho buoi sang, brunch tai quan hoac mang di." },
            items: [["Cappuccino", "Ask in store"], ["Latte", "Ask in store"], ["Flat White", "Ask in store"], ["Long Black", "Ask in store"], ["Mocha", "Ask in store"], ["Iced Latte", "Ask in store"]]
        },
        {
            slug: "drinks",
            icon: "fa-leaf",
            image: "images/coffee 2.jpg",
            name: { en: "Matcha & Cold Drinks", vi: "Matcha va do uong lanh" },
            intro: { en: "Matcha lattes, iced drinks, fresh juices and cold cafe favourites.", vi: "Matcha latte, do uong da, nuoc ep tuoi va cac mon lanh duoc yeu thich." },
            items: [["Matcha Latte", "Ask in store"], ["Iced Matcha", "Ask in store"], ["Coco Matcha", "Ask in store"], ["Fresh Juice", "Ask in store"], ["Iced Coffee", "Ask in store"], ["Smoothies", "Ask in store"]]
        },
        {
            slug: "banh-mi",
            icon: "fa-burger",
            image: "images/lounge-fish-burger.jpg",
            name: { en: "Burgers & Hot Plates", vi: "Burger va mon nong" },
            intro: { en: "Cafe lunch plates including the posted fish burger special with chips.", vi: "Cac mon an trua kieu cafe, gom burger ca dac biet an kem khoai tay chien." },
            items: [["Fish Burger Special", "$17.50"], ["Chicken Burger", "Ask in store"], ["Chicken Schnitzel", "Ask in store"], ["Fish & Chips", "Ask in store"], ["Hot Chips", "Ask in store"], ["Lunch Plate Specials", "Ask in store"]]
        },
        {
            slug: "wraps-focaccia",
            icon: "fa-utensils",
            image: "images/wraps.webp",
            name: { en: "Wraps & Sandwiches", vi: "Wrap va sandwich" },
            intro: { en: "Fresh cafe wraps and sandwiches for quick lunches, takeaway and easy table service.", vi: "Wrap va sandwich tuoi cho bua trua nhanh, mang di hoac an tai ban." },
            items: [["Grilled Chicken Wrap", "Ask in store"], ["Chicken & Avocado Wrap", "Ask in store"], ["Ham & Cheese Toastie", "Ask in store"], ["Cafe Sandwiches", "Ask in store"], ["Turkish Toastie", "Ask in store"]]
        },
        {
            slug: "vermicelli-salad-bowls",
            icon: "fa-bowl-food",
            image: "images/vermicelli bowl.avif",
            name: { en: "Salads & Bowls", vi: "Salad va bowl" },
            intro: { en: "Fresh salads, noodle salads and lighter bowls with generous portions.", vi: "Salad tuoi, noodle salad va cac bowl nhe bung voi phan an hao phong." },
            items: [["Noodle Salad", "Ask in store"], ["Chicken Salad", "Ask in store"], ["Garden Salad", "Ask in store"], ["Protein Bowl", "Ask in store"], ["Gluten-Free Friendly Options", "Ask in store"]]
        },
        {
            slug: "rice-paper-rolls",
            icon: "fa-seedling",
            image: "images/rice paper.webp",
            name: { en: "Fresh & Healthy", vi: "Mon tuoi va lanh manh" },
            intro: { en: "Quick bites, small plates and healthier cafe choices for breakfast or lunch.", vi: "Mon an nhanh, dia nho va lua chon lanh manh cho buoi sang hoac bua trua." },
            items: [["Small Plates", "Ask in store"], ["Healthy Options", "Ask in store"], ["Light Lunch", "Ask in store"], ["Gluten-Free Options", "Ask in store"], ["Outdoor Table Snacks", "Ask in store"]]
        },
        {
            slug: "salad-rolls",
            icon: "fa-glass-water",
            image: "images/coffee.jpg",
            name: { en: "Juices & Smoothies", vi: "Nuoc ep va smoothie" },
            intro: { en: "Fresh juice, colourful cold drinks and refreshing brunch pairings.", vi: "Nuoc ep tuoi, do uong lanh nhieu mau va mon uong hop voi brunch." },
            items: [["Freshly Squeezed Juice", "Ask in store"], ["Orange Juice", "Ask in store"], ["Green Juice", "Ask in store"], ["Smoothies", "Ask in store"], ["Cold Soft Drinks", "Ask in store"]]
        },
        {
            slug: "sandwiches",
            icon: "fa-bread-slice",
            image: "images/sandwiches.png",
            name: { en: "Toasties", vi: "Banh nuong" },
            intro: { en: "Simple, warm cafe toasties and easy all-day bites.", vi: "Banh nuong am nong va cac mon de an ca ngay." },
            items: [["Ham & Cheese Toastie", "Ask in store"], ["Chicken Toastie", "Ask in store"], ["Cheese Toastie", "Ask in store"], ["Sourdough Toastie", "Ask in store"]]
        },
        {
            slug: "hot-food",
            icon: "fa-fire-flame-curved",
            image: "images/lounge-fish-burger.jpg",
            name: { en: "Lunch Specials", vi: "Mon trua dac biet" },
            intro: { en: "Rotating chalkboard specials, hot lunches and comfort plates from the kitchen.", vi: "Mon dac biet tren bang, bua trua nong va cac dia an de chiu tu bep." },
            items: [["Chalkboard Special", "Ask in store"], ["Fish Burger", "$17.50"], ["Chicken Wrap Plate", "Ask in store"], ["Cafe Lunch Special", "Ask in store"], ["Chips & Salad", "Ask in store"]]
        },
        {
            slug: "slices",
            icon: "fa-cookie-bite",
            image: "images/cake.jpeg",
            name: { en: "Sweets & Bakery", vi: "Do ngot va banh" },
            intro: { en: "Banana bread, cakes, sweets and dessert cabinet treats with coffee.", vi: "Banh chuoi, banh ngot va cac mon trang mieng dung voi ca phe." },
            items: [["Banana Bread", "Ask in store"], ["Cakes", "Ask in store"], ["Dessert Cabinet", "Ask in store"], ["Sweet Treats", "Ask in store"], ["Coffee Pairings", "Ask in store"]]
        },
        {
            slug: "cakes",
            icon: "fa-child-reaching",
            image: "images/candy.webp",
            name: { en: "Kids & Family", vi: "Tre em va gia dinh" },
            intro: { en: "Family-friendly cafe picks, kids options and relaxed seating for groups.", vi: "Lua chon than thien voi gia dinh, mon cho tre em va cho ngoi thoai mai cho nhom." },
            items: [["Kids Menu", "Ask in store"], ["Kids Pancakes", "Ask in store"], ["Small Chips", "Ask in store"], ["Family Brunch", "Ask in store"], ["Group Tables", "Ask in store"]]
        }
    ],
    translations: {
        en: {
            "nav.homeAria": "Back home",
            "nav.call": "Call",
            "nav.callAria": "Call The Lounge Cafe and Eatery",
            "hero.badge": "Open daily 7am-3pm",
            "hero.title": "The Lounge",
            "hero.titleAccent": "Cafe and Eatery",
            "hero.copy": "A relaxed Logan Reserve cafe for strong coffee, matcha, breakfast, brunch, burgers, wraps, salads, juices and easy local catch-ups.",
            "hero.menuCta": "Explore Menu",
            "hero.visitCta": "Plan a Visit",
            "updates.title": "From The Lounge",
            "updates.copy": "Fresh specials, cafe favourites and a warm local table in Logan Reserve.",
            "updates.follow": "Follow @thelounge.lr",
            "updates.fishBurger": "Fish burger with crumbed fish, cheese, lettuce, tomato, sweet pickled onion and tartare sauce.",
            "updates.coffee": "Locals call out the coffee, friendly service and weekend brunch feel.",
            "updates.matcha": "Matcha, iced lattes and fresh juices sit comfortably beside cafe classics.",
            "updates.lunch": "Wraps, salads, bowls and generous plates for quick lunches or slow catch-ups.",
            "menu.title": "Menu",
            "menu.copy": "Browse the cafe favourites The Lounge is known for: coffee, matcha, breakfast, brunch, burgers, wraps, salads, juices and sweets.",
            "menu.items": "items",
            "about.eyebrow": "About us",
            "about.title": "A clean, relaxed neighbourhood cafe with a little matcha-green lift.",
            "about.p1": "The Lounge Cafe and Eatery is the easy Logan Reserve stop for breakfast, brunch, lunch and coffee, with indoor seating, outdoor tables, takeaway, kids options and friendly service.",
            "location.title": "Visit Us",
            "location.copy": "Find The Lounge at Shop 1 in Logan Reserve Shopping Village, with easy parking, takeaway and outdoor seating.",
            "location.addressLabel": "Address",
            "location.hoursLabel": "Opening Hours",
            "location.everyday": "Monday - Sunday",
            "location.contactLabel": "Contact",
            "category.back": "Back to menu",
            "category.order": "Start an order note",
            "category.count": "Menu items",
            "order.eyebrow": "Order Note",
            "order.title": "Plan a pickup request",
            "order.copy": "Use this note form to draft a pickup or group request before calling the cafe.",
            "order.back": "Back to home",
            "order.name": "Your name",
            "order.phone": "Phone number",
            "order.type": "Request type",
            "order.typeRegular": "Cafe pickup",
            "order.typeCatering": "Group / catering enquiry",
            "order.item": "Item or request",
            "order.quantity": "Quantity",
            "order.pickup": "Preferred time",
            "order.date": "Preferred date",
            "order.notes": "Notes",
            "order.submit": "Prepare note",
            "order.placeholder": "e.g. 2 fish burgers, 1 iced matcha",
            "order.notesPlaceholder": "Allergies, seating, group size or preferred pickup notes",
            "order.message": "Thanks. This demo has prepared the request, but it has not sent anything yet. Please call the cafe to confirm."
        },
        vi: {
            "nav.homeAria": "Ve trang chu The Lounge",
            "nav.call": "Goi",
            "nav.callAria": "Goi The Lounge Cafe and Eatery",
            "hero.badge": "Mo cua moi ngay 7am-3pm",
            "hero.title": "The Lounge",
            "hero.titleAccent": "Cafe and Eatery",
            "hero.copy": "Quan cafe thoai mai o Logan Reserve voi ca phe dam, matcha, bua sang, brunch, burger, wrap, salad, nuoc ep va nhung buoi gap go de chiu.",
            "hero.menuCta": "Xem thuc don",
            "hero.visitCta": "Len lich ghe tham",
            "updates.title": "Tu The Lounge",
            "updates.copy": "Mon dac biet, mon cafe duoc yeu thich va khong gian am ap tai Logan Reserve.",
            "updates.follow": "Theo doi @thelounge.lr",
            "updates.fishBurger": "Burger ca voi ca chien crumbed, pho mai, xa lach, ca chua, hanh ngam ngot va sot tartare.",
            "updates.coffee": "Khach dia phuong yeu thich ca phe, dich vu than thien va cam giac brunch cuoi tuan.",
            "updates.matcha": "Matcha, iced latte va nuoc ep tuoi nam canh cac mon cafe quen thuoc.",
            "updates.lunch": "Wrap, salad, bowl va cac dia an hao phong cho bua trua nhanh hoac buoi gap go cham rai.",
            "menu.title": "Thuc don",
            "menu.copy": "Xem cac mon duoc The Lounge biet den: ca phe, matcha, bua sang, brunch, burger, wrap, salad, nuoc ep va do ngot.",
            "menu.items": "mon",
            "about.eyebrow": "Ve chung toi",
            "about.title": "Quan cafe dia phuong sach se, thoai mai voi diem nhan xanh matcha.",
            "about.p1": "The Lounge Cafe and Eatery la diem dung de chiu o Logan Reserve cho bua sang, brunch, bua trua va ca phe, co cho ngoi trong nha, ban ngoai troi, takeaway, mon cho tre em va dich vu than thien.",
            "location.title": "Ghe tham chung toi",
            "location.copy": "The Lounge nam tai Shop 1 trong Logan Reserve Shopping Village, de dau xe, co takeaway va cho ngoi ngoai troi.",
            "location.addressLabel": "Dia chi",
            "location.hoursLabel": "Gio mo cua",
            "location.everyday": "Thu Hai - Chu Nhat",
            "location.contactLabel": "Lien he",
            "category.back": "Ve thuc don",
            "category.order": "Tao ghi chu dat mon",
            "category.count": "So mon",
            "order.eyebrow": "Ghi chu dat mon",
            "order.title": "Len yeu cau pickup",
            "order.copy": "Dung mau nay de soan yeu cau pickup hoac dat cho nhom truoc khi goi quan.",
            "order.back": "Ve trang chu",
            "order.name": "Ten cua ban",
            "order.phone": "So dien thoai",
            "order.type": "Loai yeu cau",
            "order.typeRegular": "Pickup tai quan",
            "order.typeCatering": "Hoi cho nhom / catering",
            "order.item": "Mon hoac yeu cau",
            "order.quantity": "So luong",
            "order.pickup": "Gio mong muon",
            "order.date": "Ngay mong muon",
            "order.notes": "Ghi chu",
            "order.submit": "Chuan bi ghi chu",
            "order.placeholder": "VD: 2 fish burger, 1 iced matcha",
            "order.notesPlaceholder": "Di ung, cho ngoi, so nguoi hoac ghi chu pickup",
            "order.message": "Cam on. Mau demo nay da chuan bi yeu cau nhung chua gui di. Vui long goi quan de xac nhan."
        }
    }
};
